version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama:


#########  Original commands to run containers separately in a bash file  #########

# # Run Elasticsearch in Docker
# docker run -it \
#     --rm \
#     --name elasticsearch \
#     -p 9200:9200 \
#     -p 9300:9300 \
#     -e 'discovery.type=single-node' \
#     -e 'xpack.security.enabled=false' \
#     docker.elastic.co/elasticsearch/elasticsearch:8.4.3
# &
# # Run Ollama in Docker
# docker run -it \
#   -v ollama:/root/.ollama \
#   -p 11434:11434 \
#   --name ollama \
#   ollama/ollama